---

- name: Postgres | install gpg for apt repo
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: gnupg
    state: present

- name: Postgres | get postgresql apt key
  become: true
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/postgresql.asc

- name: Postgres | setup apt repo
  become: true
  ansible.builtin.apt_repository:
    codename: "{{ ansible_distribution_release }}"
    repo: "deb [signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt/{{ ansible_distribution_release }}-pgdg main"

- name: Postgres | install client packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    name: postgresql-client-{{ postgresql_version }}
    state: present
